# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShareBox' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShareBox
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Storage'
  pod 'FBSDKLoginKit' 
end
